name: Bluesky Follow-Back Automation

on:
  schedule:
    # Runs every 2 hours for the followBack function
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  followBack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Run follow back script
        run: node src/followBack.js
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
